# Generated by Django 3.0.8 on 2020-07-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='email_contact',
        ),
    ]
