# Generated by Django 3.0.8 on 2020-07-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0002_auto_20200729_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email_contact',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
    ]
